name: GitHub Action to update version
on: push

jobs:
  replicate-file:
    runs-on: ubuntu-latest
    name: Update Version

    steps:
      - name: Checkout Project 1
        uses: actions/checkout@v2
        with:
          path: ./Project1

      - name: Checkout Project 2
        uses: actions/checkout@main
        env:
          GITHUB_TOKEN: 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
        with:
          repository: halynamecherzhak/Project2
          path: ./Project2

      - name: Read version.json file
        run: |
          content=`cat version.json`
          echo "$content"

      - name: Push Project2
        run: |
          cd ./Project2
          git add .
          git config --global user.email "galya.mech@gmail.com"
          git config --global user.name "Halyna Mecherzhak"
          git commit -am "File Replicated from Project1"
          git push
