on: push

jobs:
  replicate-file:
    runs-on: ubuntu-latest
    name: Replicate File

    steps:
      - name: Checkout Project 1
        uses: actions/checkout@v2
        with:
          path: ./Project1
      - name: Checkout Project 2
        uses: actions/checkout@main
        with:
          repository: halynamecherzhak/Project2
          token: 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
          path: ./Project2
