name: Transfer File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pushes test file
        uses: halynamecherzhak/Project1@main
        env:
          API_TOKEN_GITHUB: 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
        with:
          source_file: ""
          destination_repo: "halynamecherzhak/Project2"
          destination_folder: "Project2"
          user_email: "galya.mech@gmail.com"
          user_name: "Halyna Mecherzhak"
          commit_message: "File transfered"
