name: GitHub Action to transfer file from one repo to another
on: push

jobs:
  replicate-file:
    runs-on: ubuntu-latest
    name: Transfer File

    steps:
      - name: Checkout Project 1
        uses: actions/checkout@v2
        with:
          path: ./Project1

      - name: Checkout Project 2
        uses: actions/checkout@main
        env:
            GITHUB_TOKEN: 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
        with:
          repository: halynamecherzhak/Project2
          path: ./Project2

      - name: Copy/Create file
        run: |
          FILE=./Project1/file
          if [ -f "$FILE" ]; then
            echo "Copying $FILE"
            cp -R ./Project1/file ./Project2
          else 
            echo "Creating $FILE"
            touch ./projectB/file
          fi

        - name: Push Project2
          run: |
            cd ./Project2
            git add .
            git commit -am "File Replicated from Project1"
            git push
