on: push

jobs:
  replicate-file:
    runs-on: ubuntu-latest
    name: Replicate File

    steps:
      - name: Checkout Project 1
        uses: actions/checkout@v2
        with:
          path: ./Project1

      - name: Checkout Project 2
        uses: actions/checkout@main
        with:
          repository: halynamecherzhak/Project2
          token: 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
          path: ./Project2

      - name: Copy/Create file
        run: |
          FILE=./Project1/file
          if [ -f "$FILE" ]; then
            echo "Copying $FILE"
            cp -R ./Project1/file ./Project2
          else 
            echo "Creating $FILE"
            touch ./Project2/file
          fi
      - name: Push Project B
        run: |
          cd ./Project2
          git add .
          git commit -am "File Replicated from Project A"
          git push
